services:
    app:
        build:
            args:
                user: git
                password: Rn742NrLiE2
                uid: 1401
            context: ./
            dockerfile: bsm.dockerfile
        image: bsm-app
        container_name: bsm-app
        restart: unless-stopped
        working_dir: /var/www/html
        networks:
            - bsm-network
        ports:
            - '9018:9001'
        volumes:
            - web_root:/var/www/html
    db:
        image: postgres:16.2-alpine3.19
        command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
        container_name: bsm-db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - bsm-network
        ports:
            - '5493:5432'
        volumes:
            - ./.docker/postgres/postgresql.conf:/etc/postgresql.conf
    nginx:
        image: nginx:1.17-alpine
        container_name: bsm-app-nginx
        restart: unless-stopped
        ports:
            - 8022:80
        volumes:
            - web_root:/var/www/html
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - bsm-network
    redis:
        image: redis:7.2.4-alpine
        container_name: bsm-redis
        restart: unless-stopped
        ports:
            - 6382:6379
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
            - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - bsm-network
networks:
    bsm-network:
        driver: bridge

volumes:
    web_root:
    cache:
        driver: local

